services:
  webserver:
    container_name: nginx
    build:
      context: nginx/
    ports:
      - "8080:80"
    volumes:
      - "${PWD}/${PHP_PROJECT:?}:/var/www/html"
  php:
    container_name: php
    build:
      context: php/
    volumes:
      - "${PWD}/${PHP_PROJECT:?}:/var/www/html"
  db:
    container_name: mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
  admin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8081:80"

volumes:
  db_data:
