services:
  webserver:
    container_name: nginx
    build:
      context: nginx/
    ports:
      - "8080:80"
      - "8081:8081"
    volumes:
      - "${PHP_PROJECT:?}:/var/www/html:ro"
      - phpmyadmin:/var/www/phpmyadmin:ro
  php:
    container_name: php
    build:
      context: php/
    volumes:
      - "${PHP_PROJECT:?}:/var/www/html"
  db:
    container_name: mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
  admin:
    container_name: phpmyadmin
    image: phpmyadmin:fpm-alpine
    volumes:
      - phpmyadmin:/var/www/html

volumes:
  db_data:
  phpmyadmin:
