version: '3.9'

services:
  webserver:
    container_name: apache
    build:
      context: apache/
      dockerfile: Dockerfile.alpine
    ports:
      - "8080:80"
    volumes:
      - "${PWD}/${PHP_PROJECT:?}:/var/www/html"
      - "${PWD}/.htaccess:/var/www/html/.htaccess"
        #- "${PWD}/${PHP_PROJECT:?}:/var/www/html"
        #- "${PWD}/.htaccess:/var/www/html/.htaccess"
  db:
    container_name: mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
  admin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8081:80"

volumes:
  db_data:
