#+title: Homestead replacement
This is a Compose file that runs a set of containers to act as a Docker based
replacement to the Laravel/Homestead image.

* How to use
** Setup
In the ~env~ file, change the ~PHP_PROJECT~ environment variable to the path to
your project. For example:
#+begin_example
PHP_PROJECT=student_administration
#+end_example
When you want to start the containers, first run ~source ./env~, and then run
the ~start.sh~ script. This will launch the containers with Compose.

To view the Laravel project in the browser, visit [[http://localhost:8080]]. If all
goes well, you should your masterpiece!
** PHPMyAdmin
This container set also comes with PHPMyAdmin, to allow you to view your
database in the browser. To access, visit [[http://localhost:8081]]. If it prompts
you for a username and password, those are "root" and "secret" respectively.
* Note
If you start with a fresh project, upon viewing your project in the browser, you
might encounter this error with "connection refused". To fix this, run this
~php artisan migrate:fresh~.
* Project configuration
You will need to modify the .env file in the root of the project in order for
it to work. The required changes are:
- ~DB_USERNAME~ should be "root"
- ~DB_PASSWORD~ should be "secret"
- ~DB_HOST~ should be "mysql"
Do NOT change anything in ~docker-compose.yml~, you might break something!
