FROM alpine:latest

RUN adduser -Du 1000 apache

RUN apk add apache2 php-apache2

RUN apk add \
	php \
	php-pdo \
	php-mbstring \
	php-pdo_mysql \
	php-dom \
	php-curl \
	php-session \
	php-tokenizer \
	php-xml \
	php-fileinfo

COPY ./httpd.conf /etc/apache2/httpd.conf

CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
